name: Test nightly build
# Still trying to figure this out
on:
  schedule:
    - cron: '25 12 * * *' # test run for today

jobs:
  build:

    runs-on: windows-2019 # will be changed to 2022 after finished

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
